use UNIVER;

-- Задание 1
Select PULPIT_NAME
FROM FACULTY, PULPIT
where FACULTY.FACULTY = PULPIT.FACULTY
and FACULTY.FACULTY in (select PROFESSION.FACULTY from PROFESSION
where (	PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
			PROFESSION.PROFESSION_NAME LIKE '%технологии%'))

-- Задание 2
Select PULPIT_NAME
FROM FACULTY INNER JOIN  PULPIT
on FACULTY.FACULTY = PULPIT.FACULTY
and FACULTY.FACULTY in (select PROFESSION.FACULTY from PROFESSION
where (	PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
			PROFESSION.PROFESSION_NAME LIKE '%технологии%'))


--Задание 3

SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY
INNER JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
INNER JOIN PROFESSION ON PROFESSION.FACULTY = FACULTY.FACULTY AND
	(PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
			PROFESSION.PROFESSION_NAME LIKE '%технологии%');

--Задание 4
Select AUDITORIUM_CAPACITY, AUDITORIUM_TYPE
From AUDITORIUM a
where AUDITORIUM = (select top (1) AUDITORIUM from AUDITORIUM aa
where aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE order by AUDITORIUM_CAPACITY desc)
ORDER BY a.AUDITORIUM_CAPACITY DESC;

--Задание 5
SELECT FACULTY.FACULTY_NAME
FROM FACULTY
WHERE EXISTS (
	SELECT * FROM PULPIT
	WHERE PULPIT.FACULTY = FACULTY.FACULTY
);

--Задание 6
SELECT TOP(1)
	ISNULL((
		SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT_T = 'ОАиП'
	), 0) [ОАиП],
	ISNULL((
		SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT_T = 'БД'
	), 0) [БД],
	ISNULL((
		SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT_T = 'СУБД'
	), 0) [СУБД]
FROM PROGRESS;

-- №7
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY >= ALL (
	SELECT AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К'
) AND AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К';

-- №8
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY < ANY (
	SELECT AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К'
) AND AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К';
