--LAB 7

use UNIVER;

-- Задание 1
GO
CREATE VIEW [Преподаватель]
 AS SELECT TEACHER [код],
           TEACHER_NAME [имя преподавателя],
           GENDER [пол],
		   PULPIT [код кафедры] from TEACHER;

-- Задание 2

GO
CREATE VIEW [Количество кафедр]
	AS SELECT
		FACULTY.FACULTY_NAME,
		COUNT(PULPIT.FACULTY) [COUNT]
	FROM FACULTY
	JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY PULPIT.FACULTY, FACULTY.FACULTY_NAME;

-- Задание 3
GO
CREATE VIEW [Аудитории]
	AS SELECT
		AUDITORIUM.AUDITORIUM,
		AUDITORIUM.AUDITORIUM_TYPE
	FROM AUDITORIUM;

GO
INSERT Аудитории VALUES('316-4', 'ЛК-К');

-- Задание 4

GO
CREATE VIEW [Лекционные_Аудитории]
	AS SELECT
		AUDITORIUM.AUDITORIUM,
		AUDITORIUM.AUDITORIUM_TYPE
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE LIKE 'ЛК%' WITH CHECK OPTION;

GO
INSERT Лекционные_Аудитории VALUES('315-4', 'ЛК-К');
GO
UPDATE [Лекционные_Аудитории]
SET AUDITORIUM = '415-4'
WHERE AUDITORIUM = '315-4';

-- Задание 5

GO
CREATE VIEW [Дисциплины]
	AS SELECT TOP(10) *
	FROM SUBJECT_T
	ORDER BY SUBJECT_T.SUBJECT_NAME;

-- Задание 6

GO
ALTER VIEW [PULPIT COUNT] WITH SCHEMABINDING
	AS SELECT
		FACULTY_NAME,
		COUNT(PULPIT) [COUNT]
	FROM dbo.FACULTY
	JOIN dbo.PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY FACULTY_NAME;